### PR TITLE
Add a separate section for indexer hints

### PR DESCRIPTION
**Pull request by incrypto32**

### CODE REVIEW

**Comment by benface** [comment]
Uhhh, really not sure @leoyvens. The error is:

> Error: Route "querying-by-subgraph-id-vs-deployment-id" is not exist. Remove this field from _meta.js file

Which seems related to [this file](https://github.com/graphprotocol/docs/blob/main/website/pages/en/querying/querying-by-subgraph-id-vs-deployment-id.mdx), but unrelated to this PR. I just checked and it happens in `main` too. Tagging @saihaj and @dimaMachina in case they have any idea while I investigate.

**Comment by benface** [comment]
@leoyvens – I figured out why CI failed, and created a PR to fix it: https://github.com/graphprotocol/docs/pull/604

**Comment by benface** [comment]
@incrypto32 – Could you please rebase or merge `main` into your branch? 🙏

**Comment by incrypto32** [comment]
Done @benface.
@leoyvens The docs good enough?

**Review by leoyvens — APPROVED** [review]

**Pull request merged**
