### PR TITLE
Update matchstick examples

### PR DESCRIPTION
**Pull request by cargopete**
Updating [Matchstick ](https://github.com/LimeChain/matchstick) examples with the latest version of the framework.

### CODE REVIEW

**Comment by PtomelySoter** [comment]
This is looking great! Do we have examples for setting up tests for callHandlers? It would also be good to add in that event parameters need to match the order of the event itself.

**Comment by PtomelySoter** [comment]
Happy to come up with some copy for this. @axiomatic-aardvark

**Review by schmidsi — APPROVED** [review]
LGTM. Great improvements.

**Review by azf20 — APPROVED** [review]
Great stuff!

**Comment by azf20** [comment]
Thanks @axiomatic-aardvark! @PtomelySoter definitely good idea, but I think best to address in a separate PR

**Pull request merged**
