### PR TITLE
Choosing Russian translation for "subgraph"

### PR DESCRIPTION
**Pull request by KatyaRyazantseva**
I would recommend to choose one of the Russian translations of  "subgraph" - "субграф" or "подграф"  and keep it all across the docs. Because now you use both and it's a bit confusing, like when you use "subgraph" and "undergraph" at the same time in English. For me, "подграф" sounds better and it's easier to pronounce in Russian. Also fixed a typo.

### CODE REVIEW

**Comment by KatyaRyazantseva** [comment]
@graphprotocol/docs-reviewers

**Comment by benface** [comment]
Thank you very much for creating this PR, @KatyaRyazantseva! Please note that we use [Crowdin](https://crowdin.com) for translating content from English. Changes made directly to the translated files will be overwritten by Crowdin. See this part of the [CONTRIBUTING.md](https://github.com/graphprotocol/docs/blob/main/CONTRIBUTING.md) doc:

> Change proposals should only be made to the English language version of pages (under /pages/en/), as translations are handled by [Crowdin](https://crowdin.com/). If you spot an issue with a translation, please do open an issue to let us know!

However, I just manually made the changes you suggested in Crowdin. They should be included the next time we merge a Crowdin PR. There's also a Glossary feature in Crowdin and "subgraph" is one of the terms in it. The current Russian translation is "субграф"; I am asking the lead translator to confirm with Russian translator(s) if they are OK with changing it to "подграф".

Thanks again for your contribution!

**Comment by maxmut96** [comment]
I would prefer to use “субграф" as for me it is a bit more native. However I will stick to whatever version we will choose, there is no problem with what👍

**Comment by benface** [comment]
> I am asking the lead translator to confirm with Russian translator(s) if they are OK with changing it to "подграф".

So, turns out they want to keep using "субграф". I am reverting my change in Crowdin. Sorry. :/

**Comment by urb4n-thr34t** [comment]
Honestly, it is not "субграф", it is "сабграф". Double-check the spelling in the transcription.

**Pull request closed without merging**
