### PR TITLE
Update deploying-a-subgraph-to-hosted.mdx

### PR DESCRIPTION
**Pull request by Web3Slimchance**
Removed Rinkeby from supported networks and added information about Ropsten, Rinkeby and Kovan being deprecated.

### CODE REVIEW

**Review by ahmadmardeni1 — APPROVED** [review]

**Comment by azf20** [comment]
@Web3Slimchance thanks! I think there are some additional places where Rinkeby is mentioned, do you think it's worth doing a full sweep?

**Comment by Web3Slimchance** [comment]
Yeah - Rinkeby is mentioned multiple places. Will do a full sweep tomorrow.

**Comment by azf20** [comment]
Hey @Web3Slimchance did you manage to sweep?

**Comment by Web3Slimchance** [comment]
Wanted to run some tests to make sure the docs reflect the current capabilities of the CLI, UI and Hosted Service RPCs. 🙏

**Review by azf20 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
