### PR TITLE
Remove querying-with-no-code.mdx and update _meta.js

### PR DESCRIPTION
**Pull request by marcusrein**
Removed Dapplooker from docs.

### CODE REVIEW

**Review by schmidsi — CHANGES_REQUESTED** [review]
I'm not sure if this is sufficient. What about this page: https://github.com/graphprotocol/docs/blob/main/website/pages/en/querying/querying-with-no-code.mdx ? @benface, translations are removed simply by removing the `en` page, no? What else is needed?

**Review by benface — CHANGES_REQUESTED** [review]
Looks like you only deleted the page in two languages, not including English.

**Comment by benface** [comment]
> translations are removed simply by removing the en page, no? What else is needed?

@schmidsi – Actually no, we should manually delete pages in all languages. Annoying, and maybe there's a way to change that behavior in Crowdin, but I haven't found it.

**Review by benface — APPROVED** [review]

**Review by schmidsi — APPROVED** [review]

**Comment by marcusrein** [comment]
This update was performed as Dapplooker is a product that uses The Graph for its service. The Graph docs are meant to be a place for technical information relevant to directly building with The Graph.

**Pull request merged**
