### PR TITLE
chore: add exponential rebate tldr

### PR DESCRIPTION
**Pull request by alex-pakalniskis**
https://github.com/graphprotocol/docs/pull/454#issuecomment-1672359973

@howard-the-graph please confirm if this looks good to go.

### CODE REVIEW

**Review by howard-the-graph — COMMENTED** [review]
I recommend a minor revision to be more concise and avoid vague phrases about relative amounts:

> The exponential rebate function is proposed as a way to ensure indexers achieve the best outcome by faithfully serving queries. It works by incentivizing Indexers to allocate stake, which can be slashed for erring when serving a query.

**Comment by howard-the-graph** [comment]
Separately, the phrase "by the gateway and" should be removed from the first sentence of the paragraph.

**Review by howard-the-graph — APPROVED** [review]

**Review by azf20 — APPROVED** [review]

**Comment by benface** [comment]
@alex-pakalniskis – Uhhh yeah that's weird:

CleanShot 2023-09-12 at 11 20 34@2x

I can't imagine the change in this PR introducing any sort of failure, so I would just ignore it yes.

**Comment by benface** [comment]
cc @saihaj @B2o5T ☝️

**Pull request merged**
