### PR TITLE
removal

### PR DESCRIPTION
**Pull request by idalithb**
-Removing a straggler

### CODE REVIEW

**Comment by benface** [comment]
I think you accidentally deleted the `vi` version of the page instead of the `en` one :P

**Comment by idalithb** [comment]
I was attempting to delete this page: https://thegraph.com/docs/vi/deploying/hosted-service/

**Comment by benface** [comment]
Oh, I guess I don't understand why that one in particular? I see now that the page was already deleted in English, but not in any of the other languages.

**Comment by idalithb** [comment]
Oh, I understand now. Will it automatically be deleted in all other languages?

**Pull request closed without merging**
